### ISSUE TITLE
Virtual Enchanting not using levels or lapis with Spigot 1.8.8.

### ISSUE THREAD

**Issue by mibby** [Siguza/VirtualPack#33]
Virtual enchanting table does not seem to use levels or lapis when using in survival mode. As well as it provides the same enchant if you enchant the same type of item multiple times in a row. (Such as enchanting 3 different swords, all will have the same enchantment instead of it being random.)

VirtualPack dev 147
Spigot 1.8.8  git-Spigot-d97e08b-5e85956

**Comment by mibby** [comment]
@Siguza Downgrading to dev 146 (latest dev.bukkit.org release build) does not fix the issue.

**Comment by Siguza** [comment]
Didn't test, but should be fixed in dev build 148.

**Comment by mibby** [comment]
@Siguza Didn't fix the issue. Still doesn't give random enchants or use the lapis/exp.

```
[23:04:08] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.server.v1_8_R3.EntityHuman.b(I)V
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_51]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NoSuchMethodError: net.minecraft.server.v1_8_R3.EntityHuman.b(I)V
	at net.drgnome.virtualpack.components.VEnchantTable.a(VEnchantTable.java:165) ~[?:?]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1723) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.PacketPlayInEnchantItem.a(SourceFile:22) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.PacketPlayInEnchantItem.a(SourceFile:8) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	... 5 more
[23:04:10] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.server.v1_8_R3.EntityHuman.b(I)V
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_51]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NoSuchMethodError: net.minecraft.server.v1_8_R3.EntityHuman.b(I)V
	at net.drgnome.virtualpack.components.VEnchantTable.a(VEnchantTable.java:165) ~[?:?]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1723) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.PacketPlayInEnchantItem.a(SourceFile:22) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.PacketPlayInEnchantItem.a(SourceFile:8) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	... 5 more
```

**Comment by Siguza** [comment]
Ok, I failed.
My Jenkins was already building when I changed its config to build for 1.8.8.
Build 149 should be 1.8.8-compatible for real.

**Comment by mibby** [comment]
Confirmed fixed. Thanks.
