### ISSUE TITLE
MC 1.11 Update

### ISSUE THREAD

**Issue by mibby** [Siguza/VirtualPack#41]
Spigot for Minecraft 1.11 is out. NMS update time? :D

**Comment by lululombard** [comment]
I couldn't agree more !

**Comment by Siguza** [comment]
Should be fixed in fbdd8efd8c3c70b0be044c441dc4beb8e98b3103.
Dev builds have been updated as always, upload on Bukkit is on its way.

<sub>God, no code should be made to compile against NMS 1.8 and 1.11. Ever.</sub>

**Comment by mibby** [comment]
Thanks for the update. :) I'll be fully updating to 1.11 in the next few days. When I do, I'll test out all the VirtualPack features I use and let you know if anything isn't working as intended.

**Comment by mibby** [comment]
@Siguza Someone trying to use an Anvil.

```
[10:29:09] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException: The validated object is null
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_112]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_112]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:47) [patched_1.11.jar:git-Paper-933]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:817) [patched_1.11.jar:git-Paper-933]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.jar:git-Paper-933]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [patched_1.11.jar:git-Paper-933]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [patched_1.11.jar:git-Paper-933]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.NullPointerException: The validated object is null
	at org.apache.commons.lang3.Validate.notNull(Validate.java:222) ~[patched_1.11.jar:git-Paper-933]
	at org.apache.commons.lang3.Validate.notNull(Validate.java:203) ~[patched_1.11.jar:git-Paper-933]
	at net.minecraft.server.v1_11_R1.NonNullList.set(SourceFile:45) ~[patched_1.11.jar:git-Paper-933]
	at net.minecraft.server.v1_11_R1.PlayerInventory.setItem(PlayerInventory.java:408) ~[patched_1.11.jar:git-Paper-933]
	at net.minecraft.server.v1_11_R1.Slot.set(SourceFile:79) ~[patched_1.11.jar:git-Paper-933]
	at net.drgnome.virtualpack.components.VAnvil.b(VAnvil.java:326) ~[?:?]
	at net.minecraft.server.v1_11_R1.Container.a(Container.java:248) ~[patched_1.11.jar:git-Paper-933]
	at net.drgnome.virtualpack.components.VAnvil.a(VAnvil.java:47) ~[?:?]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1891) ~[patched_1.11.jar:git-Paper-933]
	at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.11.jar:git-Paper-933]
	at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.11.jar:git-Paper-933]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) ~[patched_1.11.jar:git-Paper-933]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_112]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_112]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) ~[patched_1.11.jar:git-Paper-933]
	... 5 more
```

**Comment by Siguza** [comment]
Should be fixed with 2.8.10 / a82fd3205d4cbf641e0e6888391f1584a1adae5c.

**Comment by mibby** [comment]
@Siguza Seems virtual anvils crash the server - using v2.8.10.

```
Description: Exception in server tick loop

java.lang.NoSuchMethodError: org.bukkit.craftbukkit.v1_11_R1.inventory.CraftInventoryAnvil.<init>(Lorg/bukkit/Location;Lnet/minecraft/server/v1_11_R1/IInventory;Lnet/minecraft/server/v1_11_R1/IInventory;)V
	at net.drgnome.virtualpack.components.VAnvil.getBukkitView(VAnvil.java:404)
	at net.drgnome.virtualpack.components.VAnvil.getBukkitView(VAnvil.java:16)
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:894)
	at net.minecraft.server.v1_11_R1.PlayerList.disconnect(PlayerList.java:407)
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1053)
	at net.minecraft.server.v1_11_R1.NetworkManager.handleDisconnection(NetworkManager.java:324)
	at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:184)
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:912)
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403)
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749)
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mibby** [comment]
Also an issue with brewing.
```
[14:30:12] [Server thread/WARN]: [VirtualPack] Task #87 for VirtualPack v2.8.10 generated an exception
java.lang.NoSuchMethodError: org.bukkit.event.inventory.BrewEvent.<init>(Lorg/bukkit/block/Block;Lorg/bukkit/inventory/BrewerInventory;)V
	at net.drgnome.virtualpack.components.VTEBrewingstand.brew(VTEBrewingstand.java:407) ~[?:?]
	at net.drgnome.virtualpack.components.VTEBrewingstand.tick(VTEBrewingstand.java:148) ~[?:?]
	at net.drgnome.virtualpack.VPack.tick(VPack.java:242) ~[?:?]
	at net.drgnome.virtualpack.VPlugin.run(VPlugin.java:1059) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.11.jar:git-Paper-953]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:355) [patched_1.11.jar:git-Paper-953]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:807) [patched_1.11.jar:git-Paper-953]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.jar:git-Paper-953]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [patched_1.11.jar:git-Paper-953]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [patched_1.11.jar:git-Paper-953]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
```

**Comment by Siguza** [comment]
I took a look at PaperSpigot, they broke compatibility with Spigot's and their own previous Bukkit API.  
My code wouldn't compile against PaperSpigot, and I'm not exactly willing to maintain yet another dependency that can change on a moment's notice. :/

**Comment by lululombard** [comment]
Damn I'm using PaperSpigot too :/

**Comment by mibby** [comment]
@Siguza I'm compiling against normal 1.11 spigot right now and it fails. So VPack isn't compliant with the latest Spigot/Bukkit API. =/

```
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.0:compile (default-compile) on project VirtualPack: Compilation failure: Compilation failure:
main/java/net/drgnome/virtualpack/components/VAnvil.java:[12,8] class VBrewingstand is public, should be declared in a file named VBrewingstand.java
main/java/net/drgnome/virtualpack/components/VBrewingstand.java:[16,8] class VAnvil is public, should be declared in a file named VAnvil.java
main/java/net/drgnome/virtualpack/components/VTEBrewingstand.java:[407,35] constructor BrewEvent in class org.bukkit.event.inventory.BrewEvent cannot be applied to given types;
required: org.bukkit.block.Block,org.bukkit.inventory.BrewerInventory,int
found: org.bukkit.block.Block,org.bukkit.craftbukkit.v1_11_R1.inventory.CraftInventoryBrewer
reason: actual and formal argument lists differ in length
main/java/net/drgnome/virtualpack/components/VBrewingstand.java:[404,66] constructor CraftInventoryAnvil in class org.bukkit.craftbukkit.v1_11_R1.inventory.CraftInventoryAnvil cannot be applied to given types;
required: org.bukkit.Location,net.minecraft.server.v1_11_R1.IInventory,net.minecraft.server.v1_11_R1.IInventory,net.minecraft.server.v1_11_R1.ContainerAnvil
found: <nulltype>,net.minecraft.server.v1_11_R1.IInventory,net.minecraft.server.v1_11_R1.IInventory
reason: actual and formal argument lists differ in length
```

**Comment by Siguza** [comment]
Wow. Same-version compatibility-breaking changes. That's a new one.
But alright, if Spigot and PaperSpigot share that, I'll take care of it.

**Comment by mibby** [comment]
Do you know how long it would take to push out a quick hotfix or is the API change something more elaborate?

**Comment by Siguza** [comment]
Revision d0449c75d0e63ac86c32d9cc0ff0dbc37c73cdbc should compile against the latest Spigot-1.11.  
Brewing Stands were an easy fix, but Anvils now swallow Enchanted Books for a reason I haven't figured out yet. I'll push the next release when I find and fix that.
For now, things should at least no longer crash.

**Comment by mibby** [comment]
Thanks for the fix. I can confirm it now compiles against the latest Spigot 1.11 API/build. Hopefully you find a fix for the anvils swalling enchanted books soon. :)

**Comment by mibby** [comment]
@Siguza Brewing stand still seems to error.

```
[15:02:09] [Server thread/WARN]: [VirtualPack] Task #85 for VirtualPack v2.8.11 generated an exception
java.lang.NullPointerException
	at net.minecraft.server.v1_11_R1.PotionBrewer.d(SourceFile:86) ~[patched_1.11.jar:git-Paper-958]
	at net.drgnome.virtualpack.components.VTEBrewingstand.processItem(VTEBrewingstand.java:553) ~[?:?]
	at net.drgnome.virtualpack.components.VTEBrewingstand.brew(VTEBrewingstand.java:418) ~[?:?]
	at net.drgnome.virtualpack.components.VTEBrewingstand.tick(VTEBrewingstand.java:148) ~[?:?]
	at net.drgnome.virtualpack.VPack.tick(VPack.java:242) ~[?:?]
	at net.drgnome.virtualpack.VPlugin.run(VPlugin.java:1059) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.11.jar:git-Paper-958]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:355) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:807) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [patched_1.11.jar:git-Paper-958]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
```

**Comment by mibby** [comment]
As well as seem to be getting this spam since putting VirtualPack pack on the server. Possible a virtual furnace is trying to constantly smelt with nothing in it, thus attempting to smelt air?

```
[15:10:04] [Server thread/WARN]: Couldn't smelt 0xtile.air@0 because there is no smelting recipe
[15:10:14] [Server thread/WARN]: Couldn't smelt 0xtile.air@0 because there is no smelting recipe
[15:10:35] [Server thread/WARN]: Couldn't smelt 0xtile.air@0 because there is no smelting recipe
[15:10:39] [Server thread/WARN]: Couldn't smelt 0xtile.air@0 because there is no smelting recipe
[15:10:42] [Server thread/WARN]: Couldn't smelt 0xtile.air@0 because there is no smelting recipe
[15:11:02] [Server thread/WARN]: Couldn't smelt 0xtile.air@0 because there is no smelting recipe
[15:11:05] [Server thread/WARN]: Couldn't smelt 0xtile.air@0 because there is no smelting recipe
```

**Comment by Siguza** [comment]
Alright, I'll look into that as well.  
Non-existent item stacks used to be `null`, but with 1.11, Mojang introduced their own version of `null`, so... there might still be a few bugs like that.

**Comment by mibby** [comment]
Hopefully they are easy fixes. Just to compile a quick small list so it isn't mistakenly forgotten;

* Anvils eating enchanted books.
* Virtual brewing NPE.
* Smelting air.

**Comment by mibby** [comment]
Do you have any estimate on how long it'll take to make the fixes? :(

**Comment by Siguza** [comment]
4451702a44ca108b7e4178cb9a166fd671eb6d00 should fix the problem with anvils and brewing stands, and hopefully also the air smelting.  
I was never able to reproduce the latter however, so could you try and check?

**Comment by mibby** [comment]
@Siguza Still erroring. :(

```
[19:14:36] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: org.bukkit.event.enchantment.PrepareItemEnchantEvent.<init>(Lorg/bukkit/entity/Player;Lorg/bukkit/inventory/InventoryView;Lorg/bukkit/block/Block;Lorg/bukkit/inventory/ItemStack;[II)V
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_112]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_112]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:47) [patched_1.11.jar:git-Paper-963]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:817) [patched_1.11.jar:git-Paper-963]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.jar:git-Paper-963]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [patched_1.11.jar:git-Paper-963]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [patched_1.11.jar:git-Paper-963]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.enchantment.PrepareItemEnchantEvent.<init>(Lorg/bukkit/entity/Player;Lorg/bukkit/inventory/InventoryView;Lorg/bukkit/block/Block;Lorg/bukkit/inventory/ItemStack;[II)V
	at net.drgnome.virtualpack.components.VEnchantTable.a(VEnchantTable.java:68) ~[?:?]
	at net.minecraft.server.v1_11_R1.ContainerEnchantTable$1.update(ContainerEnchantTable.java:28) ~[patched_1.11.jar:git-Paper-963]
	at net.minecraft.server.v1_11_R1.InventorySubcontainer.setItem(InventorySubcontainer.java:146) ~[patched_1.11.jar:git-Paper-963]
	at net.minecraft.server.v1_11_R1.Slot.set(SourceFile:79) ~[patched_1.11.jar:git-Paper-963]
	at net.minecraft.server.v1_11_R1.ContainerEnchantTable.b(ContainerEnchantTable.java:374) ~[patched_1.11.jar:git-Paper-963]
	at net.minecraft.server.v1_11_R1.Container.a(Container.java:248) ~[patched_1.11.jar:git-Paper-963]
	at net.drgnome.virtualpack.components.VEnchantTable.a(VEnchantTable.java:38) ~[?:?]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1893) ~[patched_1.11.jar:git-Paper-963]
	at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.11.jar:git-Paper-963]
	at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.11.jar:git-Paper-963]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) ~[patched_1.11.jar:git-Paper-963]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_112]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_112]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) ~[patched_1.11.jar:git-Paper-963]
	... 5 more
[19:14:39] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: org.bukkit.event.enchantment.PrepareItemEnchantEvent.<init>(Lorg/bukkit/entity/Player;Lorg/bukkit/inventory/InventoryView;Lorg/bukkit/block/Block;Lorg/bukkit/inventory/ItemStack;[II)V
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_112]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_112]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:47) [patched_1.11.jar:git-Paper-963]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:817) [patched_1.11.jar:git-Paper-963]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.jar:git-Paper-963]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [patched_1.11.jar:git-Paper-963]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [patched_1.11.jar:git-Paper-963]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.enchantment.PrepareItemEnchantEvent.<init>(Lorg/bukkit/entity/Player;Lorg/bukkit/inventory/InventoryView;Lorg/bukkit/block/Block;Lorg/bukkit/inventory/ItemStack;[II)V
	at net.drgnome.virtualpack.components.VEnchantTable.a(VEnchantTable.java:68) ~[?:?]
	at net.minecraft.server.v1_11_R1.ContainerEnchantTable$1.update(ContainerEnchantTable.java:28) ~[patched_1.11.jar:git-Paper-963]
	at net.minecraft.server.v1_11_R1.InventorySubcontainer.setItem(InventorySubcontainer.java:146) ~[patched_1.11.jar:git-Paper-963]
	at net.minecraft.server.v1_11_R1.Slot.set(SourceFile:79) ~[patched_1.11.jar:git-Paper-963]
	at net.minecraft.server.v1_11_R1.Container.a(Container.java:535) ~[patched_1.11.jar:git-Paper-963]
	at net.minecraft.server.v1_11_R1.ContainerEnchantTable.b(ContainerEnchantTable.java:365) ~[patched_1.11.jar:git-Paper-963]
	at net.minecraft.server.v1_11_R1.Container.a(Container.java:248) ~[patched_1.11.jar:git-Paper-963]
	at net.drgnome.virtualpack.components.VEnchantTable.a(VEnchantTable.java:38) ~[?:?]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1893) ~[patched_1.11.jar:git-Paper-963]
	at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.11.jar:git-Paper-963]
	at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.11.jar:git-Paper-963]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) ~[patched_1.11.jar:git-Paper-963]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_112]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_112]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) ~[patched_1.11.jar:git-Paper-963]
	... 5 more
[19:14:43] [Async Chat Thread - #19/INFO]: <Helper> Taco_Buddy: welcome to eos, qrow! good luck on the quiz!
[19:14:47] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: org.bukkit.event.enchantment.PrepareItemEnchantEvent.<init>(Lorg/bukkit/entity/Player;Lorg/bukkit/inventory/InventoryView;Lorg/bukkit/block/Block;Lorg/bukkit/inventory/ItemStack;[II)V
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_112]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_112]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:47) [patched_1.11.jar:git-Paper-963]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:817) [patched_1.11.jar:git-Paper-963]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.jar:git-Paper-963]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [patched_1.11.jar:git-Paper-963]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [patched_1.11.jar:git-Paper-963]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.enchantment.PrepareItemEnchantEvent.<init>(Lorg/bukkit/entity/Player;Lorg/bukkit/inventory/InventoryView;Lorg/bukkit/block/Block;Lorg/bukkit/inventory/ItemStack;[II)V
	at net.drgnome.virtualpack.components.VEnchantTable.a(VEnchantTable.java:68) ~[?:?]
	at net.minecraft.server.v1_11_R1.ContainerEnchantTable$1.update(ContainerEnchantTable.java:28) ~[patched_1.11.jar:git-Paper-963]
	at net.minecraft.server.v1_11_R1.InventorySubcontainer.setItem(InventorySubcontainer.java:146) ~[patched_1.11.jar:git-Paper-963]
	at net.minecraft.server.v1_11_R1.Slot.set(SourceFile:79) ~[patched_1.11.jar:git-Paper-963]
	at net.minecraft.server.v1_11_R1.ContainerEnchantTable.b(ContainerEnchantTable.java:387) ~[patched_1.11.jar:git-Paper-963]
	at net.minecraft.server.v1_11_R1.Container.a(Container.java:248) ~[patched_1.11.jar:git-Paper-963]
	at net.drgnome.virtualpack.components.VEnchantTable.a(VEnchantTable.java:38) ~[?:?]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1893) ~[patched_1.11.jar:git-Paper-963]
	at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.11.jar:git-Paper-963]
	at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.11.jar:git-Paper-963]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) ~[patched_1.11.jar:git-Paper-963]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_112]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_112]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) ~[patched_1.11.jar:git-Paper-963]
	... 5 more
```

**Comment by Siguza** [comment]
I opened an issue on Spigot, I can't work like this.

**Comment by Siguza** [comment]
Okay, apparently plugins aren't supposed to construct events. Looks like VP will no longer support them then.
cb896ee8e3091370ae2b99b4bf066d76f39ae49c should now finally fix this.

**Comment by mibby** [comment]
While most issues seem to be knocked out of the park, this one still occurs with virtualpack 2.8.11 installed.

Paper dev 1025 (Spigot 1.11.2)
VirtualPack 2.8.11

As if a virtual furnace is attempting to smelt something when it is still burning with nothing left to smelt.

```
[Server thread/WARN]: Couldn't smelt 0xtile.air@0 because there is no smelting recipe
```

**Comment by mibby** [comment]
@Siguza Also ran into this error.

```
[11:18:46] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalAccessError: tried to access method net.minecraft.server.v1_11_R1.Enchantment.a(Lnet/minecraft/server/v1_11_R1/Enchantment;)Z from class net.drgnome.virtualpack.components.VAnvil
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_112]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_112]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:47) [patched_1.11.2.jar:git-Paper-1029]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:821) [patched_1.11.2.jar:git-Paper-1029]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1029]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [patched_1.11.2.jar:git-Paper-1029]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [patched_1.11.2.jar:git-Paper-1029]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.IllegalAccessError: tried to access method net.minecraft.server.v1_11_R1.Enchantment.a(Lnet/minecraft/server/v1_11_R1/Enchantment;)Z from class net.drgnome.virtualpack.components.VAnvil
	at net.drgnome.virtualpack.components.VAnvil.e(VAnvil.java:170) ~[?:?]
	at net.minecraft.server.v1_11_R1.ContainerAnvil.a(ContainerAnvil.java:115) ~[patched_1.11.2.jar:git-Paper-1029]
	at net.drgnome.virtualpack.components.VAnvil.a(VAnvil.java:38) ~[?:?]
	at net.minecraft.server.v1_11_R1.ContainerAnvil$1.update(ContainerAnvil.java:20) ~[patched_1.11.2.jar:git-Paper-1029]
	at net.minecraft.server.v1_11_R1.InventorySubcontainer.setItem(InventorySubcontainer.java:146) ~[patched_1.11.2.jar:git-Paper-1029]
	at net.minecraft.server.v1_11_R1.Slot.set(SourceFile:79) ~[patched_1.11.2.jar:git-Paper-1029]
	at net.minecraft.server.v1_11_R1.Container.a(Container.java:535) ~[patched_1.11.2.jar:git-Paper-1029]
	at net.drgnome.virtualpack.components.VAnvil.b(VAnvil.java:310) ~[?:?]
	at net.minecraft.server.v1_11_R1.Container.a(Container.java:248) ~[patched_1.11.2.jar:git-Paper-1029]
	at net.drgnome.virtualpack.components.VAnvil.a(VAnvil.java:47) ~[?:?]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1897) ~[patched_1.11.2.jar:git-Paper-1029]
	at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.11.2.jar:git-Paper-1029]
	at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.11.2.jar:git-Paper-1029]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) ~[patched_1.11.2.jar:git-Paper-1029]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_112]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_112]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) ~[patched_1.11.2.jar:git-Paper-1029]
	... 5 more
[11:18:47] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalAccessError: tried to access method net.minecraft.server.v1_11_R1.Enchantment.a(Lnet/minecraft/server/v1_11_R1/Enchantment;)Z from class net.drgnome.virtualpack.components.VAnvil
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_112]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_112]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:47) [patched_1.11.2.jar:git-Paper-1029]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:821) [patched_1.11.2.jar:git-Paper-1029]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1029]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [patched_1.11.2.jar:git-Paper-1029]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [patched_1.11.2.jar:git-Paper-1029]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.IllegalAccessError: tried to access method net.minecraft.server.v1_11_R1.Enchantment.a(Lnet/minecraft/server/v1_11_R1/Enchantment;)Z from class net.drgnome.virtualpack.components.VAnvil
	at net.drgnome.virtualpack.components.VAnvil.e(VAnvil.java:170) ~[?:?]
	at net.drgnome.virtualpack.components.VAnvil.a(VAnvil.java:353) ~[?:?]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:2430) ~[patched_1.11.2.jar:git-Paper-1029]
	at net.minecraft.server.v1_11_R1.PacketPlayInCustomPayload.a(SourceFile:58) ~[patched_1.11.2.jar:git-Paper-1029]
	at net.minecraft.server.v1_11_R1.PacketPlayInCustomPayload.a(SourceFile:8) ~[patched_1.11.2.jar:git-Paper-1029]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) ~[patched_1.11.2.jar:git-Paper-1029]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_112]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_112]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) ~[patched_1.11.2.jar:git-Paper-1029]
	... 5 more
```

**Comment by mibby** [comment]
Bump. :(

**Comment by Siguza** [comment]
Sorry, I'm working through a backlog of support requests.
I started looking into the exception, and it's related to changes to the anvil that aren't trivial to implement. I should have a fix for that in a few days though.

**Comment by Siguza** [comment]
Ok, I just pushed some changes. It compiles under all supported versions again, but I had no time to test it.

**Comment by mibby** [comment]
Thanks for the pushed changes. Unfortunately this still occurs when VirtualPack is installed with presumably someone's virtual furnace going.

```
[10:47:06] [Server thread/WARN]: Couldn't smelt 0xtile.air@0 because there is no smelting recipe
```

**Comment by Siguza** [comment]
[Doesn't seem to be a VirtualPack issue](https://hub.spigotmc.org/jira/browse/SPIGOT-3005).

**Comment by mibby** [comment]
Hmm, quite odd. I've only noticed it occurring when I've had VPack installed, but if it is caused by players hitting rabbits with fire swords, I guess that would be the cause. What a weird vanilla bug.

**Comment by mibby** [comment]
VirtualPack v2.8.12
Paper dev 1075 (Spigot 1.11.2)

@Siguza Virtual anvil still causing an exception.

```
[13:58:54] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_121]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:47) [patched_1.11.2.jar:git-Paper-1075]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:830) [patched_1.11.2.jar:git-Paper-1075]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1075]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754) [patched_1.11.2.jar:git-Paper-1075]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652) [patched_1.11.2.jar:git-Paper-1075]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
	at net.minecraft.server.v1_11_R1.Container.a(Container.java:249) ~[patched_1.11.2.jar:git-Paper-1075]
	at net.drgnome.virtualpack.components.VAnvil.a(VAnvil.java:47) ~[?:?]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1905) ~[patched_1.11.2.jar:git-Paper-1075]
	at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.11.2.jar:git-Paper-1075]
	at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.11.2.jar:git-Paper-1075]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.11.2.jar:git-Paper-1075]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) ~[patched_1.11.2.jar:git-Paper-1075]
	... 5 more
```

**Comment by mibby** [comment]
Still happening. =/

```
[15:50:22] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_131]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_131]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:47) [patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:839) [patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:763) [patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661) [patched_1.11.2.jar:git-Paper-1104]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
	at net.minecraft.server.v1_11_R1.Container.a(Container.java:249) ~[patched_1.11.2.jar:git-Paper-1104]
	at net.drgnome.virtualpack.components.VAnvil.a(VAnvil.java:47) ~[?:?]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1906) ~[patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.11.2.jar:git-Paper-1104]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_131]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) ~[patched_1.11.2.jar:git-Paper-1104]
	... 5 more
```

**Comment by mibby** [comment]
Hopefully this issue can be fixed in 1.12. :(
```
[14:33:51] [Server thread/INFO]: player issued server command: /anvil
[14:33:53] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_131]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_131]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:47) [patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:839) [patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:763) [patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661) [patched_1.11.2.jar:git-Paper-1104]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
	at net.minecraft.server.v1_11_R1.Container.a(Container.java:249) ~[patched_1.11.2.jar:git-Paper-1104]
	at net.drgnome.virtualpack.components.VAnvil.a(VAnvil.java:47) ~[?:?]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1906) ~[patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.11.2.jar:git-Paper-1104]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_131]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) ~[patched_1.11.2.jar:git-Paper-1104]
	... 5 more
```

**Comment by mibby** [comment]
Closing because we're on 1.12 now.
